### ISSUE TITLE
Add funded accounts to setup

### ISSUE THREAD

**Issue by chopan123** [paltalabs/create-soroban-dapp#18]
## ODHack
This issue is part of ODHack:

- [Description](https://app.onlydust.com/p/get-your-soroban-journey-started-with-create-soroban-dapp)
- [Guidelines](https://onlydust.notion.site/ODHack-Guidelines-Project-leads-June-2024-209fff76da8442d6a6a49ec9fb575af8)

### Description
 
Create a script to create ten funded accounts that will be executed when starting the project, on standalone.

Also, create a function called  `getFundedAccounts` to get those funded on `.ts` file.

Deploy script should take the a`ccounts[0]` as the admin account.

### Acceptance Criteria

Accounts should be retrievable by calling the function `getFundedAccounts`

### Note
describe the structure of files (where and with which names will be saved) in a comment to be assigned to this issue

**Comment by RajeshRk18** [comment]
Hey @chopan123! Here is how I will go about resolving this issue;

- I will add a new field called `ChildAccounts` in `EnvConfig` [here](https://github.com/paltalabs/create-soroban-dapp/blob/main/soroban-react-dapp/contracts/utils/env_config.ts) which will store the newly created accounts.

- I will create a new file called `get_funded_accounts.ts` and implement `getFundedAccounts` fn to retrieve all funded accounts. This function will accept `EnvConfig` object to extract the funded account keys and get their balances. Otherwise, when creating `EnvConfig` object from the `configs.json`, we can add each account's secret to environment, so  we can use `getUser` fn to get key pair and use it to retieve the balance.

**Comment by jedstroke** [comment]
GM @chopan123, here's my portfolio: https://www.jedshock.com/. I hope I am deem fit enough to tackle on this issue?
