### ISSUE TITLE
Make the containers' names depend on project-name

### ISSUE THREAD

**Issue by chopan123** [paltalabs/create-soroban-dapp#49]
## Problem Statement

**Description**: When running the `npx create-soroban-dapp@latest` or `npm create soroban-dapp@latest` script for multiple projects, users encounter an error when attempting to run containers from those multiple projects simultaneously. This issue arises because the containers share the same names, leading to conflicts.
Error message when running containers in multiple projects:
```
Recreating soroban-preview ... 
stellar is up-to-date

ERROR: for soroban-preview  'ContainerConfig'

ERROR: for soroban-preview  'ContainerConfig'
Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose/cli/main.py", line 81, in main
  File "compose/cli/main.py", line 203, in perform_command
  File "compose/metrics/decorator.py", line 18, in wrapper
  File "compose/cli/main.py", line 1186, in up
  File "compose/cli/main.py", line 1182, in up
  File "compose/project.py", line 702, in up
  File "compose/parallel.py", line 108, in parallel_execute
  File "compose/parallel.py", line 206, in producer
  File "compose/project.py", line 688, in do
  File "compose/service.py", line 581, in execute_convergence_plan
  File "compose/service.py", line 503, in _execute_convergence_recreate
  File "compose/parallel.py", line 108, in parallel_execute
  File "compose/parallel.py", line 206, in producer
  File "compose/service.py", line 496, in recreate
  File "compose/service.py", line 615, in recreate_container
  File "compose/service.py", line 334, in create_container
  File "compose/service.py", line 922, in _get_container_create_options
  File "compose/service.py", line 962, in _build_container_volume_options
  File "compose/service.py", line 1549, in merge_volume_bindings
  File "compose/service.py", line 1579, in get_container_data_volumes
KeyError: 'ContainerConfig'
[48270] Failed to execute script docker-compose
```

**Impact of the Problem**: This conflict prevents developers from running multiple instances of the project simultaneously, which can significantly hinder productivity, especially in environments where multiple projects are being developed and tested concurrently.

## Proposed Solution

**Overview**: Modify the container naming convention in the create-soroban-dapp script to include the project name as a suffix. This will ensure that each project's containers have unique names, allowing them to run simultaneously without conflicts.

**Detailed Explanation**: Update the Docker Compose configuration within the `create-soroban-dapp` script to dynamically generate container names based on the project name. This could involve appending or prepending the project name to the container names (e.g., soroban-preview-projectname).

## Acceptance Criteria

**Specific Requirements:**
- Containers should be named with a unique identifier based on the project name.
-  The script should run without errors when multiple projects are executed 
-  No regression issues should be introduced in the naming convention or container functionality.

**Test Cases:**
- [ ] Verify that containers from different projects have unique names and can run simultaneously without 
- [ ] Test the script with multiple projects to ensure that the naming convention works as expected.
- [ ] Check `run.sh` script

## Technical Details

**Implementation Notes**: Modify the Docker Compose configuration within the create-soroban-dapp script to include a variable for the project name. This variable should be used to generate container names dynamically.

Dependencies: The project name should be passed as a command-line argument when the script is executed.

## Impact Analysis

Impact on Existing Features: This change will primarily impact the naming of containers. Care should be taken to ensure that any tooling or scripts dependent on container names are updated accordingly.

**Comment by Iwueseiter** [comment]
Hi @chopan123 can I work on this?

**Comment by Naomi-Gift** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/get-your-soroban-journey-started-with-create-soroban-dapp).

### My background and how it can be leveraged
@chopan123 Hi
Can I please work on this issue?
I am a frontend/web3 developer

### How I plan on tackling this issue
1. Update the `create-soroban-dapp` script to append the project name to container names for uniqueness.
2. Modify Docker Compose to dynamically generate these names based on the project name provided as a command-line argument.
3. Test with multiple projects to ensure containers run simultaneously without conflicts and maintain compatibility.

**Comment by adrianvrj** [comment]
hey can I work on this one?

**Comment by od-hunter** [comment]
Hi @chopan123 , please can I work on this? I’ll raise a pr ASAP.

**Comment by ShantelPeters** [comment]
Hello @chopan123 , please can I work this issue ?

**Comment by martinvibes** [comment]
hello @chopan123 i would love to work on this as this will be my first contributing to your repo

**Comment by chopan123** [comment]
Just remember you need to be registered in Only Dust to be assigned! We start tommorrow!

**Comment by od-hunter** [comment]
> Just remember you need to be registered in Only Dust to be assigned! We start tommorrow!

I have registered on Onlydust already ser.

**Comment by Dprof-in-tech** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/get-your-soroban-journey-started-with-create-soroban-dapp).

### My background and how it can be leveraged
As an experienced Full Stack Blockchain Developer, I'm excited to contribute my expertise to Edition 7 of the OnlyDust hackathons. With a strong background in Next.js, TypeScript, JavaScript, React, Node.js, Solidity, and Cairo, I've honed my technical skills across the blockchain development landscape.
My journey with OnlyDust began at Edition 2, and I've since made 28 contributions across 11 projects. This extensive experience on the platform has allowed me to develop a keen understanding of delivering high-quality solutions under tight deadlines. I bring a unique blend of technical prowess and user-centric design to every project, whether I'm crafting immersive 3D experiences or developing innovative smart contracts.
My track record demonstrates my ability to adapt quickly and contribute effectively to diverse challenges. I'm confident in my capacity to tackle new problems and drive innovation in the blockchain space. As we embark on Edition 7, I'm eager to leverage my hackathon experience and technical skills to push the boundaries of what's possible in blockchain development.
With a passion for creating cutting-edge solutions, I'm excited to collaborate with the OnlyDust community and contribute to the advancement of the blockchain ecosystem.


### How I plan on tackling this issue
To solve this issue, i will:

Update Docker Compose Configuration
Modify the Docker Compose configuration within the create-soroban-dapp script to dynamically generate container names.
Implement a method to append or prepend the project name to the container names (e.g., soroban-preview-projectname).
Implement Project Name Handling
Add functionality to capture and use the project name as a variable in the script.
Ensure this variable is correctly passed to the Docker Compose configuration.
Modify Container Naming Logic
Update the container naming logic in the script to incorporate the project name.
Ensure all relevant containers (e.g., soroban-preview, stellar) use the new naming convention.
Update run.sh Script
Review and modify the run.sh script to accommodate the new naming convention.
Ensure any references to container names are updated to use the new dynamic naming.
Testing
Verify that containers from different projects have unique names and can run simultaneously without conflicts.
Test the script with multiple projects to ensure the naming convention works as expected.
Check for any regression issues in container functionality.
Documentation Update
Update any relevant documentation to reflect the changes in container naming.
Provide clear instructions for users on how the new naming convention works.

**Comment by Ugo-X** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/get-your-soroban-journey-started-with-create-soroban-dapp).

### My background and how it can be leveraged
I am a Full Stack blockchain Developer with expertise in Next.js, Nest.js, TypeScript, JavaScript, React, Node.js, Three.js, and Solidity. My journey with OnlyDust hackathons began at Edition 1, and I've since made 47 contributions across 11 projects. With my extensive experience on the OnlyDust platform (profile:  https://app.onlydust.com/u/Ugo-X), I've honed my skills in delivering quality solutions under pressure.
I bring a unique blend of technical proficiency and user-focused design to every project, whether it's crafting immersive 3D experiences or developing smart contracts. My track record shows I can adapt quickly and contribute effectively to diverse challenges.
As we surf through Edition 7, I'm excited to leverage my skills and hackathon experience to push the boundaries of blockchain development. I'm confident in my ability to tackle new challenges and drive innovation in this space.

### How I plan on tackling this issue
I will modify the create-soroban-dapp script to incorporate unique container names for each project, allowing multiple projects to run simultaneously without conflicts. Here's how I'll approach this:

1. Update Docker Compose Configuration:
   I will modify the Docker Compose configuration in the create-soroban-dapp script to use dynamic container names. This will involve:
   a. Generating a unique identifier for each project based on its directory name or a user-provided name.
   b. Updating the container_name fields in the Docker Compose YAML to include this unique identifier.

2. Implement Unique Identifier Generation:
   I will create a function that generates a unique identifier for each project. This function will:
   a. Use the project's directory name as a base.
   b. Append a short hash or timestamp to ensure uniqueness.
   c. Sanitize the identifier to ensure it's valid for Docker container names.

3. Modify Container Naming:
   I will update the container names in the Docker Compose file to use the unique identifier:
   a. Change "soroban-preview" to "soroban-preview-${PROJECT_ID}"
   b. Change "stellar" to "stellar-${PROJECT_ID}"

4. Update Run Scripts:
   I will modify the run.sh script to:
   a. Generate and export the PROJECT_ID environment variable.
   b. Pass this PROJECT_ID to the Docker Compose commands.

5. Error Handling and Feedback:
   I will implement error handling to:
   a. Detect if containers with conflicting names already exist.
   b. Provide clear error messages and suggestions if conflicts occur.

6. Testing:
   I will thoroughly test the solution by:
   a. Running multiple instances of create-soroban-dapp in different directories.
   b. Verifying that containers from different projects can run simultaneously.
   c. Ensuring that existing functionality remains intact.

7. Documentation:
   I will update the project documentation to:
   a. Explain the new naming convention for containers.
   b. Provide instructions for users who need to interact with these containers directly.

This focused solution directly addresses the container naming conflict without adding unnecessary complexity. It allows developers to run multiple Soroban projects simultaneously, improving productivity and development workflow.

**Comment by ScottyDavies** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/get-your-soroban-journey-started-with-create-soroban-dapp).

### My background and how it can be leveraged
I am front end developer with 6 years experience. 
i have worked with microsoft on several projects,
this will be my first time contributing to the hackathon and i am ready to work

### How I plan on tackling this issue
I would approach this issue with following steps
Issue
When running the npx create-soroban-dapp@latest or npm create soroban-dapp@latest script for multiple projects, users encounter an error when attempting to run containers from those multiple projects simultaneously. This is because the containers share the same names, leading to conflicts.

Proposed Solution

Modify the container naming convention in the create-soroban-dapp script to include the project name as a suffix. This will ensure that each project's containers have unique names, allowing them to run simultaneously without conflicts.
Update the Docker Compose configuration within the create-soroban-dapp script to dynamically generate container names based on the project name. This could involve appending or prepending the project name to the container names (e.g., soroban-preview-projectname).
Acceptance Criteria

Containers should be named with a unique identifier based on the project name.
The script should run without errors when multiple projects are executed.
No regression issues should be introduced in the naming convention or container functionality.
Test Cases

Verify that containers from different projects have unique names and can run simultaneously without conflicts.
Test the script with multiple projects to ensure that the naming convention works as expected.
Check the run.sh script for any necessary updates.
Implementation Notes

Modify the Docker Compose configuration within the create-soroban-dapp script to include a variable for the project name.
Use this variable to generate container names dynamically.
Impact Analysis
This change will primarily impact the naming of containers. Care should be taken to ensure that any tooling or scripts dependent on container names are updated accordingly.

**Comment by bitfalt** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/get-your-soroban-journey-started-with-create-soroban-dapp).

### My background and how it can be leveraged
Hii, my name is Daniel. I'm a software and web3 developer. I've dealt with Docker issues and configuration throughout my University courses to optimize deployment and simplify the experience of teammates. I have a good understanding of creating Docker Compose configuration files. I'm also a member of the Dojo Coding community and have contributed to this project before.

### How I plan on tackling this issue
The way I would tackle the issue is in the following way:
- Add a variable for the proejct name as per the implementation notes.
- Add the project name as command-line argument per the implementation notes
- Modify the Docker Compose file so that the containers' names are assigned dinamically and not static.
- If any issues or questions arise during my implementation, I will ask one of the maintainers for help.

**Comment by DIWAKARKASHYAP** [comment]
https://diwakar-portfolio.vercel.app/  i want to work on this issue
